Feature/img resize
gustavoalbert-smps/school_action pull request #16
Opened 2022-11-01 00:20 UTC by isaiasaraujosilva

Finalizando a implementação do upload da foto do perfil

2022-11-01 12:03 UTC, gustavoalbert-smps commented on src/Infrastructure/Repository/PdoPhotoRepository.php
> +        $altura = "200";
Não esquecer de colocar as variáveis em inglês.

2022-11-01 12:07 UTC, gustavoalbert-smps requested changes
Alterações aprovadas. Não esquecer de colocar as variáveis em inglês.

2022-11-01 23:35 UTC, isaiasaraujosilva commented
Realizado a alteração da linguagem das variaveis

2022-11-03 00:11 UTC, gustavoalbert-smps approved these changes
Alterações aprovadas.

2022-11-03 00:12 UTC, merged